<?php

return [
    'team-admin' => [
        'users.create',
        'users.update',
        'users.list',
        'users.delete',
        //
        'customers.create',
        'customers.update',
        'customers.list',
        'customers.delete',
        //
        'services.all-services',
        'services.assign',
        'services.create',
        'services.update',
        'services.list',
        'services.delete',
        //
        'services-types.create',
        'services-types.update',
        'services-types.list',
        'services-types.delete',
        //
        'profile.view',
        'profile.edit',
        //
        'team.show',
        'team.edit',
        //
        'config.general',
        'config.services-types',
        'config.polls',
        //
        'stats.view'
    ],
    'despachador' => [
        'services.all-services',
        'services.assign',
        'services.create',
        'services.update',
        'services.list',
        'services.delete',
        //
        'profile.view',
        'profile.edit',
        //
        'team.show',
        //
        'config.general',
        'config.services-types',
        'config.polls',
    ],
    'rutero' => [
        'services.list',
        'profile.view',
        'profile.edit',
    ],

    // TOdos los permisos para iterarlos
    'all' => [
        'users.create',
        'users.update',
        'users.list',
        'users.delete',
        //
        'customers.create',
        'customers.update',
        'customers.list',
        'customers.delete',
        //
        'services.all-services',
        'services.assign',
        'services.create',
        'services.update',
        'services.list',
        'services.delete',
        //
        'services-types.create',
        'services-types.update',
        'services-types.list',
        'services-types.delete',
        //
        'profile.view',
        'profile.edit',
        //
        'team.show',
        'team.edit',
        //
        'config.general',
        'config.services-types',
        'config.polls',
        //
        'stats.view'
    ]
];